version: '3.8'
services:
  backend:
    volumes:
      - ./backend:/app
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://hermes_mongo:27017/portfolio
    ports:
      - "5000:5000"
  frontend:
    volumes:
      - ./frontend:/app
    container_name: hermes_frontend_dev
    build: null
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "3005:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
